name: Package Source Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - uses: actions/upload-artifact@master
        with:
          name: source_code
          path: .
